name: Update GitHub Profile README
on:
  push:
  schedule:
    - cron: "* * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update GitHub Profile README
      uses: theboi/github-update-readme@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: "Hi I'm Leon, or am I?"
        subhead: "These are some of the projects I have worked on: \n- [Terraria mods](https://github.com/users/NotLe0n/projects/2)\n- [UIGenerator](https://github.com/NotLe0n/UIGenerator)\n[Test Platformer](https://github.com/bafto/Platformer) with a [Level Editor](https://github.com/NotLe0n/LevelEditor)\n- [ModStatistics](https://github.com/NotLe0n/ModStats) (defunct)\n- [tmlAPI](https://github.com/NotLe0n/tmlapis) (orig by me, rewritten in Go by [@bafto](https://github.com/bafto))\n- [DynamicTMLStats](https://github.com/NotLe0n/DynamicTMLStats) (thanks [@bafto](https://github.com/bafto))\n### Some fun stats:\n[![NotLe0ns's GitHub stats](https://github-readme-stats.vercel.app/api?username=NotLe0n&show_icons=true&theme=tokyonight)](https://github.com/anuraghazra/github-readme-stats)\n![card](https://dynamictmlstats.repl.co/?steamid64=76561198278789341)"
